-- Use drop statements for developers, once the database is set we should delete these dangerous lines
 drop table if exists competition cascade;
 drop table if exists team cascade;
 drop table if exists comp_team_mapping cascade;
 drop table if exists match;
 drop table if exists pit;

create table competition (
    competition_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_name varchar(255) NOT NULL,
    blue_key varchar(15) NOT NULL,
    is_current boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT competition_unique_key UNIQUE (short_name)
);

INSERT INTO competition (short_name, blue_key, is_current) VALUES ('PAL', 'scmb', TRUE);
INSERT INTO competition (short_name, blue_key, is_current) VALUES ('HVR', 'nysu', FALSE);
INSERT INTO competition (short_name, blue_key, is_current) VALUES ('SBPLI', 'nyli2', FALSE);
INSERT INTO competition (short_name, blue_key, is_current) VALUES ('NYC', 'nyny', FALSE);
INSERT INTO competition (short_name, blue_key, is_current) VALUES ('Champs', 'cmpmi' ,FALSE);


create table team (
    team_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_num int NOT NULL,
    team_name varchar(100),
    CONSTRAINT team_unique_key UNIQUE (team_num)
);

insert into team (team_num, team_name) values (108, 'SigmaC@T Robotics Team');
insert into team (team_num, team_name) values (281, 'The GreenVillains');
insert into team (team_num, team_name) values (283, 'The Generals');
insert into team (team_num, team_name) values (342, 'Burning Magnetos');
insert into team (team_num, team_name) values (343, 'Metal-In-Motion');
insert into team (team_num, team_name) values (694, 'StuyPulse');
insert into team (team_num, team_name) values (744, 'Shark Attack');
insert into team (team_num, team_name) values (846, 'The Funky Monkeys');
insert into team (team_num, team_name) values (1051, 'Technical Terminators');
insert into team (team_num, team_name) values (1287, 'Aluminum Assault');
insert into team (team_num, team_name) values (1293, 'Pandamaniacs');
insert into team (team_num, team_name) values (1319, 'Flash');
insert into team (team_num, team_name) values (1369, 'Minotaur');
insert into team (team_num, team_name) values (1398, 'Robo-Raiders');
insert into team (team_num, team_name) values (1539, 'Royal Robotics');
insert into team (team_num, team_name) values (1553, 'KC Robotics Team');
insert into team (team_num, team_name) values (1708, "AMP'D Robotics");
insert into team (team_num, team_name) values (1758, 'Technomancers');
insert into team (team_num, team_name) values (2183, 'Tigerbots');
insert into team (team_num, team_name) values (2187, 'Team Volt');
insert into team (team_num, team_name) values (2614, 'Mountaineer Area RoboticS (MARS)');
insert into team (team_num, team_name) values (2815, 'Blue Devil Mechanics');
insert into team (team_num, team_name) values (3140, 'Flagship');
insert into team (team_num, team_name) values (3489, 'Category 5');
insert into team (team_num, team_name) values (3490, 'Viper Drive');
insert into team (team_num, team_name) values (3492, 'Putnam Area Robotics Team (P.A.R.T.s)');
insert into team (team_num, team_name) values (3651, 'TRIBE');
insert into team (team_num, team_name) values (3653, 'BOTCATS');
insert into team (team_num, team_name) values (3824, 'HVA RoHAWKtics');
insert into team (team_num, team_name) values (3976, 'Electric Hornets');
insert into team (team_num, team_name) values (4020, 'Cyber Tribe');
insert into team (team_num, team_name) values (4050, 'Biohazard');
insert into team (team_num, team_name) values (4073, 'Robo Katz');
insert into team (team_num, team_name) values (4074, 'Shark Bytes');
insert into team (team_num, team_name) values (4075, 'Robo Tigers');
insert into team (team_num, team_name) values (4083, 'The Iron Wolverines');
insert into team (team_num, team_name) values (4243, 'Excelsior!');
insert into team (team_num, team_name) values (4267, 'Brave Bots');
insert into team (team_num, team_name) values (4451, 'ROBOTZ Garage');
insert into team (team_num, team_name) values (4471, 'SPARTRONS');
insert into team (team_num, team_name) values (4533, 'Wando Advanced Robotics');
insert into team (team_num, team_name) values (4582, 'Robohawks');
insert into team (team_num, team_name) values (4748, 'Bulldog Autobots');
insert into team (team_num, team_name) values (4764, 'The Memphis MechWarriors');
insert into team (team_num, team_name) values (4847, 'Techno-Logic Trojans');
insert into team (team_num, team_name) values (4965, 'FIRE');
insert into team (team_num, team_name) values (5022, 'Rat Rod Robotics');
insert into team (team_num, team_name) values (5063, 'BuzzBots');
insert into team (team_num, team_name) values (5130, 'Undercogs');
insert into team (team_num, team_name) values (5317, '@RedhawkRobotics');
insert into team (team_num, team_name) values (5410, 'Eaglebotics');
insert into team (team_num, team_name) values (5472, 'Stallion Robotics: The Wyld Stallyns');
insert into team (team_num, team_name) values (5777, 'Static Storm');
insert into team (team_num, team_name) values (5842, 'Royal Robotics');
insert into team (team_num, team_name) values (5943, 'The Bad News Gears');
insert into team (team_num, team_name) values (6167, 'CB Bearbots');
insert into team (team_num, team_name) values (6222, 'Flying Tigers');
insert into team (team_num, team_name) values (6366, 'RAM Rodz Robotics');
insert into team (team_num, team_name) values (6626, 'Robohana');
insert into team (team_num, team_name) values (6693, 'TrailBLAZERS');
insert into team (team_num, team_name) values (6961, 'SIbots');
insert into team (team_num, team_name) values (7085, 'Paranoid Androids');
insert into team (team_num, team_name) values (7431, 'Wingspan');
insert into team (team_num, team_name) values (8137, 'Byting Bulldogs');

create table comp_team_mapping (
 mapping_id bigint generated by default as identity primary key,
 competition_id int references competition (competition_id) not null,
 team_id int references team (team_id) not null,
 constraint comp_team_mapping_unique_key unique (competition_id, team_id)
);

insert into comp_team_mapping (competition_id, team_id) values (1,1);
insert into comp_team_mapping (competition_id, team_id) values (1,2);
insert into comp_team_mapping (competition_id, team_id) values (1,3);
insert into comp_team_mapping (competition_id, team_id) values (1,4);
insert into comp_team_mapping (competition_id, team_id) values (1,5);
insert into comp_team_mapping (competition_id, team_id) values (1,6);
insert into comp_team_mapping (competition_id, team_id) values (1,7);
insert into comp_team_mapping (competition_id, team_id) values (1,8);
insert into comp_team_mapping (competition_id, team_id) values (1,9);
insert into comp_team_mapping (competition_id, team_id) values (1,10);
insert into comp_team_mapping (competition_id, team_id) values (1,11);
insert into comp_team_mapping (competition_id, team_id) values (1,12);
insert into comp_team_mapping (competition_id, team_id) values (1,13);
insert into comp_team_mapping (competition_id, team_id) values (1,14);
insert into comp_team_mapping (competition_id, team_id) values (1,15);
insert into comp_team_mapping (competition_id, team_id) values (1,16);
insert into comp_team_mapping (competition_id, team_id) values (1,17);
insert into comp_team_mapping (competition_id, team_id) values (1,18);
insert into comp_team_mapping (competition_id, team_id) values (1,19);
insert into comp_team_mapping (competition_id, team_id) values (1,20);
insert into comp_team_mapping (competition_id, team_id) values (1,21);
insert into comp_team_mapping (competition_id, team_id) values (1,22);
insert into comp_team_mapping (competition_id, team_id) values (1,23);
insert into comp_team_mapping (competition_id, team_id) values (1,24);
insert into comp_team_mapping (competition_id, team_id) values (1,25);
insert into comp_team_mapping (competition_id, team_id) values (1,26);
insert into comp_team_mapping (competition_id, team_id) values (1,27);
insert into comp_team_mapping (competition_id, team_id) values (1,28);
insert into comp_team_mapping (competition_id, team_id) values (1,29);
insert into comp_team_mapping (competition_id, team_id) values (1,30);
insert into comp_team_mapping (competition_id, team_id) values (1,31);
insert into comp_team_mapping (competition_id, team_id) values (1,32);
insert into comp_team_mapping (competition_id, team_id) values (1,33);
insert into comp_team_mapping (competition_id, team_id) values (1,34);
insert into comp_team_mapping (competition_id, team_id) values (1,35);
insert into comp_team_mapping (competition_id, team_id) values (1,36);
insert into comp_team_mapping (competition_id, team_id) values (1,37);
insert into comp_team_mapping (competition_id, team_id) values (1,38);
insert into comp_team_mapping (competition_id, team_id) values (1,39);
insert into comp_team_mapping (competition_id, team_id) values (1,40);
insert into comp_team_mapping (competition_id, team_id) values (1,41);
insert into comp_team_mapping (competition_id, team_id) values (1,42);
insert into comp_team_mapping (competition_id, team_id) values (1,43);
insert into comp_team_mapping (competition_id, team_id) values (1,44);
insert into comp_team_mapping (competition_id, team_id) values (1,45);
insert into comp_team_mapping (competition_id, team_id) values (1,46);
insert into comp_team_mapping (competition_id, team_id) values (1,47);
insert into comp_team_mapping (competition_id, team_id) values (1,48);
insert into comp_team_mapping (competition_id, team_id) values (1,49);
insert into comp_team_mapping (competition_id, team_id) values (1,50);
insert into comp_team_mapping (competition_id, team_id) values (1,51);
insert into comp_team_mapping (competition_id, team_id) values (1,52);
insert into comp_team_mapping (competition_id, team_id) values (1,53);
insert into comp_team_mapping (competition_id, team_id) values (1,54);
insert into comp_team_mapping (competition_id, team_id) values (1,55);
insert into comp_team_mapping (competition_id, team_id) values (1,56);
insert into comp_team_mapping (competition_id, team_id) values (1,57);
insert into comp_team_mapping (competition_id, team_id) values (1,58);
insert into comp_team_mapping (competition_id, team_id) values (1,59);
insert into comp_team_mapping (competition_id, team_id) values (1,60);
insert into comp_team_mapping (competition_id, team_id) values (1,61);
insert into comp_team_mapping (competition_id, team_id) values (1,62);
insert into comp_team_mapping (competition_id, team_id) values (1,63);
insert into comp_team_mapping (competition_id, team_id) values (1,64);

create table match (
    match_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mapping_id int references comp_team_mapping(mapping_id) NOT NULL,
    match_num varchar(20) NOT NULL,
    scout_name varchar(100),
    report_status varchar(30) NOT NULL DEFAULT 'NOT STARTED',
    alliance_station varchar(20),
    auto_team boolean,
    auto_power_cells int,
    starting_position varchar(20),
    cross_line varchar(10),
    auto_scored json,
    auto_comments text,
    teleop_scored json,
    rotation_control varchar(30),
    rotation_timer int,
    position_control varchar(30),
    position_timer int,
    end_game varchar(30),
    end_game_timer int,
    climb varchar(20),
    level varchar(20),
    level_position decimal,
    communication varchar(10),
    break varchar(10),
    negatives json,
    reflection_comments text,
    scout_name_super_driving varchar(100),
    scout_name_super_defense varchar(100),
    alliance_color varchar(10),
    team_order_driving int,
    team_order_defense int,
    report_status_super_driving varchar(30) NOT NULL DEFAULT 'NOT STARTED',
    report_status_super_defense varchar(30) NOT NULL DEFAULT 'NOT STARTED',
    auto_team_super_driving boolean,
    auto_team_super_defense boolean,
    speed int,
    agility int,
    counter_defense int,
    pinning_defense int, 
    knock_defense int,
    block_defense int,
    super_comments_driving text,
    super_comments_defense text,
    last_modified timestamp(0) NOT NULL DEFAULT (now())::timestamp(0),
    CONSTRAINT match_composite_key UNIQUE (mapping_id, match_num)
);


create table pit (
    pit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mapping_id int references comp_team_mapping(mapping_id) NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'NOT STARTED',
    group_name varchar(30),
    weight decimal,
    height decimal,
    drive_train varchar(30),
    motors json,
    wheels json,
    drive_comments text,
    code_language varchar(10),
    starting_position varchar(20),
    auto_comments text,
    abilities json,
    working_comments text,
    closing_comments text,
    image varchar,
    last_modified timestamp(0) NOT NULL DEFAULT (now())::timestamp(0),
    CONSTRAINT mapping_key UNIQUE (mapping_id)
);

 drop table if exists users;
 drop type if exists user_role;

create type user_role as enum ('admin', 'scout');

create table users (
  user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  role user_role NOT NULL
);

-- User table must be plural, user is reserved word
